"""Flashcard service with SM-2 spaced repetition algorithm."""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta


@dataclass
class SM2Result:
    """Result of SM-2 algorithm calculation."""

    easiness_factor: float
    interval: int  # Days
    repetitions: int
    next_review_date: datetime


def calculate_sm2(
    quality: int,
    easiness_factor: float,
    interval: int,
    repetitions: int,
) -> SM2Result:
    """
    Calculate new SM-2 values based on quality of recall.

    The SM-2 algorithm (SuperMemo 2) is a spaced repetition algorithm
    that adjusts review intervals based on how well you remember.

    Args:
        quality: Quality of recall (0-5)
            0 - Complete blackout
            1 - Incorrect, but remembered upon seeing answer
            2 - Incorrect, but seemed easy to recall
            3 - Correct with serious difficulty
            4 - Correct with hesitation
            5 - Perfect recall
        easiness_factor: Current easiness factor (minimum 1.3)
        interval: Current interval in days
        repetitions: Number of successful repetitions

    Returns:
        SM2Result with new values
    """
    # Ensure quality is in valid range
    quality = max(0, min(5, quality))

    # Calculate new easiness factor
    # EF' = EF + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02))
    new_ef = easiness_factor + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02))
    new_ef = max(1.3, new_ef)  # Minimum EF is 1.3

    # Calculate new interval and repetitions
    if quality < 3:
        # Failed recall - reset
        new_repetitions = 0
        new_interval = 1
    else:
        # Successful recall
        new_repetitions = repetitions + 1

        if repetitions == 0:
            new_interval = 1
        elif repetitions == 1:
            new_interval = 6
        else:
            new_interval = round(interval * new_ef)

    # Calculate next review date
    next_review = datetime.utcnow() + timedelta(days=new_interval)

    return SM2Result(
        easiness_factor=round(new_ef, 2),
        interval=new_interval,
        repetitions=new_repetitions,
        next_review_date=next_review,
    )


def quality_from_rating(rating: str) -> int:
    """
    Convert user-friendly rating to SM-2 quality score.

    Args:
        rating: One of 'again', 'hard', 'good', 'easy'

    Returns:
        SM-2 quality score (0-5)
    """
    rating_map = {
        'again': 1,  # Complete failure
        'hard': 3,   # Correct with difficulty
        'good': 4,   # Correct with some hesitation
        'easy': 5,   # Perfect recall
    }
    return rating_map.get(rating.lower(), 3)


def get_review_stats(
    total_cards: int,
    new_cards: int,
    due_cards: int,
    mastered_cards: int,
) -> dict:
    """
    Calculate review statistics for display.

    Returns:
        Dictionary with statistics
    """
    learning_cards = total_cards - new_cards - mastered_cards

    return {
        'total_cards': total_cards,
        'new_cards': new_cards,
        'learning_cards': learning_cards,
        'mastered_cards': mastered_cards,
        'due_cards': due_cards,
        'completion_percent': round(mastered_cards / total_cards * 100, 1) if total_cards > 0 else 0,
    }


def generate_anki_export(deck_title: str, cards: list[dict], include_tags: bool = True) -> str:
    """
    Generate Anki-compatible export file content.

    Args:
        deck_title: Title for the Anki deck
        cards: List of cards with 'front', 'back', and optional 'tags' keys
        include_tags: Whether to include tags in export

    Returns:
        Tab-separated text content for Anki import
    """
    lines = [
        f"# Deck: {deck_title}",
        "# Generated by AI Textbook Platform",
        "# https://github.com/your-repo/ai-textbook",
        "#separator:tab",
        "#html:true",
        "#columns:front\tback" + ("\ttags" if include_tags else ""),
        "",
    ]

    for card in cards:
        front = escape_anki_field(card.get('front', ''))
        back = escape_anki_field(card.get('back', ''))

        if include_tags and 'tags' in card:
            tags = ' '.join(card.get('tags', []))
            lines.append(f"{front}\t{back}\t{tags}")
        else:
            lines.append(f"{front}\t{back}")

    return '\n'.join(lines)


def escape_anki_field(text: str) -> str:
    """
    Escape text for Anki TSV format.

    Args:
        text: Raw text content

    Returns:
        Escaped text safe for Anki import
    """
    if not text:
        return ''

    # Replace tabs with spaces
    text = text.replace('\t', '    ')
    # Convert newlines to HTML breaks
    text = text.replace('\n', '<br>')
    # Escape quotes if present
    if '\t' in text or '"' in text:
        text = '"' + text.replace('"', '""') + '"'

    return text


def generate_anki_apkg_metadata(deck_title: str, deck_description: str = '') -> dict:
    """
    Generate metadata for APKG package creation.

    Note: Full APKG generation requires additional libraries (genanki).
    This provides the metadata structure for integration.

    Args:
        deck_title: Title for the Anki deck
        deck_description: Optional deck description

    Returns:
        Dictionary with deck metadata
    """
    import hashlib
    from datetime import datetime

    # Generate a consistent deck ID from the title
    deck_id = int(hashlib.md5(deck_title.encode()).hexdigest()[:8], 16)

    return {
        'deck_id': deck_id,
        'deck_name': deck_title,
        'deck_description': deck_description,
        'model_id': deck_id + 1,
        'model_name': f'{deck_title} Model',
        'created_at': datetime.utcnow().isoformat(),
        'fields': [
            {'name': 'Front', 'ord': 0},
            {'name': 'Back', 'ord': 1},
        ],
        'templates': [
            {
                'name': 'Card 1',
                'qfmt': '{{Front}}',
                'afmt': '{{FrontSide}}<hr id="answer">{{Back}}',
            }
        ],
        'css': '''
.card {
    font-family: arial;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
}
'''
    }


@dataclass
class AnkiExportResult:
    """Result of Anki export operation."""

    content: str
    filename: str
    card_count: int
    format: str  # 'tsv' or 'apkg'
    metadata: dict | None = None


def create_anki_export(
    deck_title: str,
    cards: list[dict],
    format: str = 'tsv',
    include_tags: bool = True,
    deck_description: str = '',
) -> AnkiExportResult:
    """
    Create a complete Anki export package.

    Args:
        deck_title: Title for the deck
        cards: List of flashcards
        format: Export format ('tsv' for text, 'apkg' for package)
        include_tags: Whether to include tags
        deck_description: Optional deck description

    Returns:
        AnkiExportResult with content and metadata
    """
    # Sanitize deck title for filename
    safe_title = ''.join(c if c.isalnum() or c in ' -_' else '_' for c in deck_title)
    safe_title = safe_title.strip().replace(' ', '_')[:50]

    if format == 'tsv':
        content = generate_anki_export(deck_title, cards, include_tags)
        return AnkiExportResult(
            content=content,
            filename=f'{safe_title}.txt',
            card_count=len(cards),
            format='tsv',
        )

    elif format == 'apkg':
        # For APKG, we return the metadata and TSV content
        # Full APKG generation would require genanki library
        content = generate_anki_export(deck_title, cards, include_tags)
        metadata = generate_anki_apkg_metadata(deck_title, deck_description)

        return AnkiExportResult(
            content=content,
            filename=f'{safe_title}.apkg',
            card_count=len(cards),
            format='apkg',
            metadata=metadata,
        )

    else:
        raise ValueError(f"Unsupported export format: {format}")


def estimate_study_time(due_cards: int, avg_time_per_card: float = 15.0) -> dict:
    """
    Estimate time needed for review session.

    Args:
        due_cards: Number of cards due
        avg_time_per_card: Average seconds per card

    Returns:
        Dictionary with time estimates
    """
    total_seconds = due_cards * avg_time_per_card

    return {
        'cards': due_cards,
        'seconds': total_seconds,
        'minutes': round(total_seconds / 60, 1),
        'formatted': f"{int(total_seconds // 60)}m {int(total_seconds % 60)}s",
    }
